---
# tasks file for roles/web       
- name: Installation Nginx 
      apt: 
        name: ['nginx']
        update_cache: yes

- name: Install git
      apt: 
        name: git
        state: present
        update_cache: yes

- name :  Récupération HTML file
  git:
    repo: https://github.com/nicolas-hermosilla/TP_final_jenkins_pipeline2
    dest: /var/www/html
    clone: yes



